import Head from 'next/head'
import Sections from '../../components/Sections'

const SectionsPage = () => {
  return (
    <>
      <Head>
        <title>Sections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>
      <Sections />
    </>
  )
}

export default SectionsPage
