import Head from 'next/head'
import Login from '../../components/Login'
import Products from '../../components/Products'

const LoginPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Products />
    </>
  )
}

export default LoginPage
