import Head from 'next/head'
import Completeorder from '../../components/Completeorder'

const completeorder = () => {
    return (
        <>
            <Head>
                <title>Complete Order</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Completeorder />
        </>
    )
}

export default completeorder
